# Generated by Django 3.2.9 on 2022-11-27 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=100, unique=True)),
                ('telefone', models.CharField(max_length=24)),
                ('cep', models.CharField(blank=True, max_length=8, verbose_name='cep')),
                ('rua', models.CharField(blank=True, max_length=100, verbose_name='rua')),
                ('numero', models.IntegerField(blank=True, null=True, verbose_name='numero')),
                ('data_cliente', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ('cliente',),
            },
        ),
    ]
