# Generated by Django 3.2.9 on 2022-11-29 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
        ('saida', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoque_itens_saida',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliente.cliente'),
        ),
    ]
